### ISSUE TITLE
SOAP server ?

### ISSUE THREAD

**Issue by ThierryMallard** [tozd/docker-sympa#4]
Hello there.
I think the SOAP server provided with Sympa isn't working with this configuration. Possibly because the "/sympasoap" URL for SOAP services is understood as "/sympa" with "soap" action by the fastcgi configuration.
Will work on this, but maybe you encountered the same problem ?
Best regards

**Comment by mitar** [comment]
I have not used SOAP with Sympa, so not sure. 

Probably you just have to add:

```
    location /sympasoap {
        include fastcgi_sympa_soap;
    }
``

To `etc/nginx/sites-enabled/default`, and then do something similar to `etc/service/wwsympa/run` for Sympa SOAP fcgi script, and then create `fastcgi_sympa_soap` which points to it.

PR is welcome.

**Comment by OlivierGuilloux** [comment]
I have upgrade the source in order add SOAP support. 

You can find the source in the fork https://github.com/OlivierGuilloux/docker-sympa

Regards.

**Comment by mitar** [comment]
Nice. Do patches apply cleanly to new versions? We can then just bump version here.

I do not think making version a env variable works. You were able to bump the version with that? Without changing the Dockerfile?

I think we could pull these changes in. They work for you?

**Comment by OlivierGuilloux** [comment]
You are right the VERSION works only with 6.1.23. I have rollback the changes.
I confirm the SOAP service works fine. The build is OK and I can create list using the soap service after configuring trusted application.

**Comment by mitar** [comment]
I think your fork looks awesome, but there are too many changes to integrate them nicely.
